### ISSUE TITLE
Resize form to center on screen and have better view

### ISSUE THREAD

**Issue by arthurbdiniz** [SIGS-UnB/core#110]
## Problem description
The inputs fields are to large on screen

## Expected Behavior
Inputs center on screen with reduce width

## Current Behavior

![image](https://user-images.githubusercontent.com/18387694/47877384-85bb3080-ddfa-11e8-9bb2-ea98b48ad7c7.png)

**Comment by toshitapandey** [comment]
@arthurbdiniz If this is not already done, can I pick this up?
