### ISSUE TITLE
Sidebar dont fit all screen

### ISSUE THREAD

**Issue by arthurbdiniz** [SIGS-UnB/core#126]
## Problem description

![image](https://user-images.githubusercontent.com/18387694/48322225-a0b54e00-e60d-11e8-8765-eef9289281e9.png)]

path: /rooms/index

## Expected Behavior
Fit all screen height

**Comment by arthurbdiniz** [comment]
![image](https://user-images.githubusercontent.com/18387694/58220843-d6d33900-7ce6-11e9-9acf-19f4fb3cc9dd.png)

**Comment by drianne** [comment]
This issue was solved in some old pr as can we see :

![image](https://user-images.githubusercontent.com/16694289/60748271-703a6f80-9f62-11e9-83e9-27e5c587c93f.png)
