### ISSUE TITLE
Apresentação final

### ISSUE THREAD

**Issue by arthurbdiniz** [SIGS-UnB/core#147]
## Show Me The Code 01

![image](https://user-images.githubusercontent.com/18387694/49598581-1808a400-f966-11e8-8aef-d92611920f1c.png)

#### Débitos Técnicos - 6 .  :construction:
- Melhorar formulário tela de login #7 
- Upload de imagem de perfil para usuários #34 
- Protótipo seguindo matricula web #46 
- Novo design da home baseado no prototipo #47 
- Refatoração da tela de Solicitar Cadastro #56 
- Footer escondendo parte do conteúdo das tabelas #59 

#### Concluído - 17   :white_check_mark:
- Configurar Test Reporter CC #49 @sconetto 
- Remoção do Vagrant Machine e Puppet #41 @sconetto 
- Mostrar capacidade das salas #38 @arthurbdiniz 
- Banco de dados iniciando depois do Rails #31 @victorcmoura 
- Salvar todas as chaves em um arquivo com gpg #30 @arthurbdiniz 
- Refatorar navbar #28  @arthurbdiniz e @RomeuCarvalhoAntunes
- Separar a view da navbar e footer da camada da aplicação  #24  @arthurbdiniz
- Nome errado Tela novos usuários #22 @arthurbdiniz
- Separar protótipo do projeto #17 @arthurbdiniz
- Reconfigurar as ferramentas de CI/CD #12 @sconetto 
- Atualizar os templates e adicionar documentação #9 @sconetto e @RomeuCarvalhoAntunes
- Atualizar versão das Gems #8 @arthurbdiniz
- Separar o docker-compose #4 @victorcmoura 
- Deploy contínuo #52 @sconetto 
- Separar predios por campus #37 @victorcmoura 
- Melhora na experiência de usuário com o filtro de salas #55 @victorcmoura 
- Indicador de tempo na tabela de alocações deve ser mais intuitivo #13 @victorcmoura 

## Show Me The Code 02
![image](https://user-images.githubusercontent.com/18387694/49598637-3373af00-f966-11e8-89a9-188c481dc1c4.png)

#### Débitos Técnicos - 2 . :construction:
- Novo design da home baseado no protótipo #47 
- Routing to profile page by username #95 

#### Concluído - 15  :white_check_mark:
- Seeds rooms #96 @victorcmoura 
- Restructure routes and views of athentication #93 @arthurbdiniz
- Mensagem de diálogo para edição de usuário #84 @sconetto
- Remove popup notifications #76 @arthurbdiniz
- Register SIGS Domain #86 @sconetto
- Update README #78 and #82 by: @trevlewis and @sconetto
- Upload de imagem de perfil para usuários #34 @sconetto
- Password Strength Meter #73  by: @fer22f 
- Melhorar formulário tela de login #7 @RomeuCarvalhoAntunes e @arthurbdiniz
- Refatoração da tela de Solicitar Cadastro #56  @arthurbdiniz
- Mostrar mensagem de inexistência de solicitações abertas #62 @hugomartins013 
- Footer escondendo parte do conteúdo das tabelas #59 @victorcmoura 
- Aprimoramento do Deploy #63 @sconetto
- Protótipo seguindo matricula web #46 @arthurbdiniz
- Error no deploy (sshpass) #70 @sconetto

## Show Me The Code 03
![image](https://user-images.githubusercontent.com/18387694/49598659-3ec6da80-f966-11e8-80ba-92316d456839.png)

#### Concluído - 15  :white_check_mark:
- Refatoração dos métodos de criação de relatório #130 @victorcmoura 
- Refatoração da Solicitations Controller #129 @RomeuCarvalhoAntunes
- Remove validations methods from models SOLID #127 @kairon-v
- Refactor sidebar in modules #122 @arthurbdiniz
- Refactor navbar #123 @arthurbdiniz
- Remove duplicated code #106 @sconetto #117 @RomeuCarvalhoAntunes 
- Create components folder from css files #111 @arthurbdiniz
- Create Home button on side bar #114 @arthurbdiniz
- seeds.rb presents bad maintainability and high churn #108 @victorcmoura 
- Novo design da home baseado no protótipo #47 @arthurbdiniz @RomeuCarvalhoAntunes @lucashm @victorcmoura 
- Reduce migrations #102 @arthurbdiniz
- Toggle password visibility #72 @sconetto
- New design to form de edit class_room #89 @hugomartins013 

## Débitos Técnicos :construction:
![image](https://user-images.githubusercontent.com/18387694/49598769-7f265880-f966-11e8-8934-f7ee4b182633.png)

#### Concluído :white_check_mark:
- Bug when deploy to docker hub #151 @sconetto
- Criar docker-compose do ambiente de homolog #148 @arthurbdiniz
- Implements watchtower on deploy #146 @arthurbdiniz
- Criar task para alimentar a aplicação com dados da API do MatriculaWeb #140 @victorcmoura 
 - Remover página de parser de CSV #131 @victorcmoura e @arthurbdiniz
- Sidebar dont fit all screen #126 @arthurbdiniz
- Tamanho das particles não ocupando tela toda #142 @arthurbdiniz
- Refactor sidebar in modules #122 @arthurbdiniz
- Remove duplicated code #106 @sconetto #117 @RomeuCarvalhoAntunes 
- Clean Code aplication in user_controller #154 @hugomartins013 
- SOLID principle aplication in solicitation model and room_solicitation model #139 @hugomartins013 

![image](https://user-images.githubusercontent.com/18387694/49598942-e2b08600-f966-11e8-92ea-0b565e76d6bc.png)
![image](https://user-images.githubusercontent.com/18387694/49598955-e93efd80-f966-11e8-95f1-df9a8f5ea9e5.png)

## Cumulative flow

![image](https://user-images.githubusercontent.com/18387694/49599041-1b505f80-f967-11e8-86de-799fb0b1c238.png)

![image](https://user-images.githubusercontent.com/18387694/49599053-24d9c780-f967-11e8-9d12-dac52a09ead0.png)

**Comment by RomeuCarvalhoAntunes** [comment]
- Refatoração do layout da aplicação 
- Integração com as matérias do MW
- Banco de dados com as salas (Maior massa de test) 
- Deploy

**Comment by hugomartins013** [comment]
Aplicação de princííos SOLID e de clean code

**Comment by RomeuCarvalhoAntunes** [comment]
## Participação
1 - [Refatoração da Tela de Login](https://github.com/SIGS-UnB/core/pull/36)
2 - [Tela Inicial da aplicação](https://github.com/SIGS-UnB/core/pull/51)
3 - [Clean COde](https://github.com/SIGS-UnB/core/pull/119/commits)
4 - [Solid](https://github.com/SIGS-UnB/core/pull/135)
5 - [Click bug front](https://github.com/SIGS-UnB/core/pull/152)
![image](https://user-images.githubusercontent.com/18054053/49588347-9c9af880-f94d-11e8-823a-d1ea17ec520c.png)
