### ISSUE TITLE
Screenshots da nova aplicação

### ISSUE THREAD

**Issue by victorcmoura** [SIGS-UnB/core#157]
Esta issue apresenta nos comentários, imagens da nova aplicação para serem mostradas na apresentação final.

**Comment by victorcmoura** [comment]
Página inicial:
![image](https://user-images.githubusercontent.com/26290053/49599611-98300900-f968-11e8-91ac-644456b2bed4.png)

**Comment by victorcmoura** [comment]
Solicitar cadastro:
![image](https://user-images.githubusercontent.com/26290053/49599770-ec3aed80-f968-11e8-82df-1a42239cfbb9.png)

**Comment by victorcmoura** [comment]
Dashboard inicial:
![image](https://user-images.githubusercontent.com/26290053/49599903-30c68900-f969-11e8-9885-098d5be25d87.png)

**Comment by victorcmoura** [comment]
Gerenciar turmas:
![image](https://user-images.githubusercontent.com/26290053/49599944-46d44980-f969-11e8-8e1f-69629b1d94ed.png)

**Comment by victorcmoura** [comment]
Lista de salas:
![image](https://user-images.githubusercontent.com/26290053/49600583-ada63280-f96a-11e8-92eb-80c5c2e729b4.png)

**Comment by victorcmoura** [comment]
Minha conta:
![image](https://user-images.githubusercontent.com/26290053/49600677-ecd48380-f96a-11e8-80ba-fa742cca36b0.png)

**Comment by sconetto** [comment]
Listagem de Solicitação:
![image](https://user-images.githubusercontent.com/11671985/49602061-af71f500-f96e-11e8-9e94-6c39995aeaad.png)


Visualização de Solicitação:
![image](https://user-images.githubusercontent.com/11671985/49602023-98cb9e00-f96e-11e8-9d9a-90ebecbf9eaa.png)
