### ISSUE TITLE
Remove Current Behavior from Issue template

### ISSUE THREAD

**Issue by arthurbdiniz** [SIGS-UnB/core#160]
## Problem description
Remove current behavior from issue template because it makes duplicity

## Expected Behavior
No Current Behavior
![image](https://user-images.githubusercontent.com/18387694/49618395-946ba900-f99f-11e8-8618-8b81628d48d4.png)

## Possible Solution
Adjust template

**Comment by toshitapandey** [comment]
@arthurbdiniz I am willing to pick this up. Is that ok?

**Comment by arthurbdiniz** [comment]
> @arthurbdiniz I am willing to pick this up. Is that ok?

Thats ok, we will be waiting your pull request!

**Comment by toshitapandey** [comment]
@arthurbdiniz PR for this issue: https://github.com/SIGS-UnB/core/pull/164

Please take a look.

**Comment by arthurbdiniz** [comment]
Thanks @toshitapandey, i have just merged the PR!
