### ISSUE TITLE
Delete button doesn't delete a room

### ISSUE THREAD

**Issue by drianne** [SIGS-UnB/core#171]
## Problem description

It's impossible to delete a room of  **/rooms/index**.

## Expected Behavior

When you try to delete a room it delete and redirects to the rooms/index.

## Step to Reproduce (for _bugs_)

1. Go to **/ rooms / index**
2. Click any option button in any room
   ![image](https://user-images.githubusercontent.com/18387694/49346500-90c3e380-f67a-11e8-8c77-79c30f5e9e2a.png)
3. Click in 'Deletar' option 
4. It doesn't works 

## Screenshots

After try to delete S4 room, it doesn't work. 
![image](http://uploaddeimagens.com.br/images/002/032/244/full/Captura_de_tela_de_2019-04-11_17-14-47.png?1555013720)

**Comment by arthurbdiniz** [comment]
@drianne this issue may already have been resolved by the #144. Make sure everything is okay.

**Comment by drianne** [comment]
> @drianne this issue may already have been resolved by the #144. Make sure everything is okay.

The #144 issue was about the button redirection however there is a bug when I try to delete a room. Would I keep this issue to solve this?

**Comment by arthurbdiniz** [comment]
Sure keep this issue and solve this bug
