### ISSUE TITLE
Appoint coordinator in profile

### ISSUE THREAD

**Issue by mlfaa** [SIGS-UnB/core#203]
## Problem description
Doesn't have the coordinator's indication on the profile  and the name. 

## Expected Behavior
Appoint coordinator's indication on the profile and the name.  

## Screenshots

Name
![image](https://uploaddeimagens.com.br/images/002/065/737/original/Captura_de_tela_de_2019-04-25_17-31-36.png?1556224316)

Profile
![image](https://uploaddeimagens.com.br/images/002/065/746/original/Captura_de_tela_de_2019-04-25_17-32-42.png?1556224371)

**Comment by drianne** [comment]
Is this issue finished? @nukdown
