### ISSUE TITLE
Routing to profile page by username

### ISSUE THREAD

**Issue by arthurbdiniz** [SIGS-UnB/core#91]
## Problem description
The profile page its been routed by user ID
![image](https://user-images.githubusercontent.com/18387694/47046513-a1240b80-d16b-11e8-8481-e1d12286dc61.png)

## Expected Behavior
Routing by username
![image](https://user-images.githubusercontent.com/18387694/47046529-aed99100-d16b-11e8-987a-f3ce438e1d16.png)

## Possible Solution
https://stackoverflow.com/questions/32750164/routing-to-profile-page-by-username

**Comment by toshitapandey** [comment]
@arthurbdiniz Is this assigned, or shall i pick it up?

**Comment by arthurbdiniz** [comment]
Sure @toshitapandey , we will be waiting for your PR

**Comment by arthurbdiniz** [comment]
> @arthurbdiniz Is this assigned, or shall i pick it up?

**Comment by arthurbdiniz** [comment]
Ignore this :point_up:

**Comment by nukdown** [comment]
actualy i cant progress on this issue because i got error on tests from cucumber. If anyone have a ideia to solve this error please call me.
![errorcucumber](https://user-images.githubusercontent.com/21694288/56992614-d248b400-6b70-11e9-9553-dd2b9de424cd.png)

**Comment by nukdown** [comment]
https://github.com/SIGS-UnB/core/commit/92a3d6ec0d6cd07daba7581ddf049f1714dd16cb
This commit remove lines of core needed for this enhancement feature. Need back the modifications for development branch.

**Comment by nukdown** [comment]
This issues has been closed, but need refactory some unit test to verify if endpoint are returned with slug.

**Comment by filypsdias** [comment]
Is this issue already solved?
